source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SGProgressIndicator_Example', :exclusive => true do
  pod 'SGProgressIndicator', :path => '../'
end

target 'SGProgressIndicator_Tests', :exclusive => true do
  pod 'SGProgressIndicator', :path => '../'

  
end
